### ISSUE TITLE
编码错误

### ISSUE THREAD

**Issue by Yangyu53** [taishan1994/OneRel_chinese#1]
运行train.py时会出现如下错误：
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 961316: ordinal not in range(128)
貌似是python版本的问题还是其他...？
可以说一下python的版本吗，谢谢！

> > 运行train.py时会出现如下错误： UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 961316: ordinal not in range(128) 貌似是python版本的问题还是其他...？ 可以说一下python的版本吗，谢谢！
> 
> python3.6 你这是在打开哪个文件出现的错误

是其他python包版本配错了，现已成功跑通，感谢作者！

**Comment by taishan1994** [comment]
> 运行train.py时会出现如下错误： UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 961316: ordinal not in range(128) 貌似是python版本的问题还是其他...？ 可以说一下python的版本吗，谢谢！

python3.6 你这是在打开哪个文件出现的错误
