### ISSUE TITLE
关于用tensorflow复现OneRel

### ISSUE THREAD

**Issue by Fraudsterrrr** [taishan1994/OneRel_chinese#14]
你好 最近想使用tensorflow2.x去复现 OneRel 的代码做中文的关系抽取，复现了模型，但是因为不太了解pytorch训练和数据处理流程，看的不太明白，可以提供一句样例和该样例预处理后的矩阵结果吗。 非常感谢！

**Comment by taishan1994** [comment]
> 你好 最近想使用tensorflow2.x去复现 OneRel 的代码做中文的关系抽取，复现了模型，但是因为不太了解pytorch训练和数据处理流程，看的不太明白，可以提供一句样例和该样例预处理后的矩阵结果吗。 非常感谢！

你看data_loader.py里面就好了。
