### ISSUE TITLE
怎样处理不含triple的句子

### ISSUE THREAD

**Issue by XuperX** [taishan1994/OneRel_chinese#28]
您好，
我正在做实验得到的结果有限，希望能请教下您如何处理无标注的句子。

在提供的所有训练集里，每段句子都存在至少一个triple，但在现实的文本中很多句子是不存在triple的。不知道您是怎么处理这类空句子的呢？

谢谢

**Comment by taishan1994** [comment]
可以改造一下，标签矩阵里面都为0。
