### ISSUE TITLE
OneRel是不是只能判断三元组，不能判断实体类型？

### ISSUE THREAD

**Issue by 976230600** [taishan1994/OneRel_chinese#29]
求问，因为我想在OneRel提取之后接一个补全算法，但是发现OneRel的输入输出好像都没有涉及实体类型，不知道是不是没有判断实体类型的设计？如果没有，我再想想办法……

**Comment by taishan1994** [comment]
onrel是获取不到实体类型的。

**Comment by 976230600** [comment]
> onrel是获取不到实体类型的。

 如果把实体类型作为一种关系，让他学习比如 [奥巴马，人物，奥巴马] 这样的三元组，我试试看有没有可能

**Comment by zjutnlper** [comment]
不能

**Comment by XuperX** [comment]
> > onrel是获取不到实体类型的。
> 
> 如果把实体类型作为一种关系，让他学习比如 [奥巴马，人物，奥巴马] 这样的三元组，我试试看有没有可能

OneRel的triple 是 【original text 1， relationship label，original text 2】

如果只把实体类型作为关系的话，没办法提供original text 2，论文里的horn脚状结构也就没法成型。按照这种方法，把第二个original text换做和第一个一样，或者加一个类似于【sep】的占位符，不知道会不会有变化。希望知道你的实验结论！

**Comment by 976230600** [comment]
> > > onrel是获取不到实体类型的。
> > 
> > 
> > 如果把实体类型作为一种关系，让他学习比如 [奥巴马，人物，奥巴马] 这样的三元组，我试试看有没有可能
> 
> OneRel的triple 是 【original text 1， relationship label，original text 2】
> 
> 如果只把实体类型作为关系的话，没办法提供original text 2，论文里的horn脚状结构也就没法成型。按照这种方法，把第二个original text换做和第一个一样，或者加一个类似于【sep】的占位符，不知道会不会有变化。希望知道你的实验结论！

我就是直接把text2做成和text1一样的，试验了一下，效果很好，唯一问题可能是识别出的实体不一定正确和完整，可能会和其他正常关系的三元组中的实体存在出入

**Comment by XuperX** [comment]
> > > > onrel是获取不到实体类型的。
> > > 
> > > 
> > > 如果把实体类型作为一种关系，让他学习比如 [奥巴马，人物，奥巴马] 这样的三元组，我试试看有没有可能
> > 
> > 
> > OneRel的triple 是 【original text 1， relationship label，original text 2】
> > 如果只把实体类型作为关系的话，没办法提供original text 2，论文里的horn脚状结构也就没法成型。按照这种方法，把第二个original text换做和第一个一样，或者加一个类似于【sep】的占位符，不知道会不会有变化。希望知道你的实验结论！
> 
> 我就是直接把text2做成和text1一样的，试验了一下，效果很好，唯一问题可能是识别出的实体不一定正确和完整，可能会和其他正常关系的三元组中的实体存在出入

棒！ 非常受启发，多谢！

**Comment by 976230600** [comment]
> > > > > onrel是获取不到实体类型的。
> > > > 
> > > > 
> > > > 如果把实体类型作为一种关系，让他学习比如 [奥巴马，人物，奥巴马] 这样的三元组，我试试看有没有可能
> > > 
> > > 
> > > OneRel的triple 是 【original text 1， relationship label，original text 2】
> > > 如果只把实体类型作为关系的话，没办法提供original text 2，论文里的horn脚状结构也就没法成型。按照这种方法，把第二个original text换做和第一个一样，或者加一个类似于【sep】的占位符，不知道会不会有变化。希望知道你的实验结论！
> > 
> > 
> > 我就是直接把text2做成和text1一样的，试验了一下，效果很好，唯一问题可能是识别出的实体不一定正确和完整，可能会和其他正常关系的三元组中的实体存在出入
> 
> 棒！ 非常受启发，多谢！



> > > > > onrel是获取不到实体类型的。
> > > > 
> > > > 
> > > > 如果把实体类型作为一种关系，让他学习比如 [奥巴马，人物，奥巴马] 这样的三元组，我试试看有没有可能
> > > 
> > > 
> > > OneRel的triple 是 【original text 1， relationship label，original text 2】
> > > 如果只把实体类型作为关系的话，没办法提供original text 2，论文里的horn脚状结构也就没法成型。按照这种方法，把第二个original text换做和第一个一样，或者加一个类似于【sep】的占位符，不知道会不会有变化。希望知道你的实验结论！
> > 
> > 
> > 我就是直接把text2做成和text1一样的，试验了一下，效果很好，唯一问题可能是识别出的实体不一定正确和完整，可能会和其他正常关系的三元组中的实体存在出入
> 
> 棒！ 非常受启发，多谢！

没事哈哈，我也还在思考这里怎么更好地抽取实体类型，后续我还想接上其他同时需要实体类型和三元组的模型，两边实体有出入就会比较难搞，有思路可以多交流
