### ISSUE TITLE
抽取的结果

### ISSUE THREAD

**Issue by WHW-S** [taishan1994/OneRel_chinese#5]
抽取的结果会显示实体对应的类型吗，比如在这里，{"text": "基于此，母亲王桂荃忍痛把幼子梁思礼送到美国，学习西方先进的科学技术，希望他学成后回来报效祖国", "spo_list": [{"predicate": "母亲", "object_type": {"@value": "人物"}, "subject_type": "人物", "object": {"@value": "王桂荃"}, "subject": "梁思礼"}]}王桂荃显示为人物

**Comment by taishan1994** [comment]
> 抽取的结果会显示实体对应的类型吗，比如在这里，{"text": "基于此，母亲王桂荃忍痛把幼子梁思礼送到美国，学习西方先进的科学技术，希望他学成后回来报效祖国", "spo_list": [{"predicate": "母亲", "object_type": {"@value": "人物"}, "subject_type": "人物", "object": {"@value": "王桂荃"}, "subject": "梁思礼"}]}王桂荃显示为人物

不会显示对应的类型的，有一种方式是知道了关系以及关系对应的实体的类型，可以反推出实体的属性，比如母亲关系，主体和客体就都是人物类型。
